### ISSUE TITLE
aesm::message::Request: sgxregisterreq missing

### ISSUE THREAD

**Issue by trosan** [01org/linux-sgx#199]
Compiling 2.1 fails with the following error message:

> sdk_sgx/psw/ae/aesm_service/source/aesm_wrapper/inc -Isource/protobuf -c ../common//src/ProtobufSerializer.cpp -o ProtobufSerializer.o
../common//src/ProtobufSerializer.cpp: In member function ‘virtual IAERequest* ProtobufSerializer::inflateRequest(AEMessage*)’:
../common//src/ProtobufSerializer.cpp:107:21: error: ‘class aesm::message::Request’ has no member named ‘has_sgxregisterreq’; did you mean ‘has_reporterrreq’?
     else if(reqMsg->has_sgxregisterreq() == true)
                     ^~~~~~~~~~~~~~~~~~
../common//src/ProtobufSerializer.cpp:108:52: error: ‘class aesm::message::Request’ has no member named ‘sgxregisterreq’; did you mean ‘reporterrreq’?
         request = new AESGXRegisterRequest(reqMsg->sgxregisterreq());
                                                    ^~~~~~~~~~~~~~
Makefile:311: recipe for target 'ProtobufSerializer.o' failed

As far as I could track it down, it's caused by psw/ae/aesm_service/source/protobuf/message.proto lacking the field sgxregisterreq.

**Comment by yuyuany** [comment]
Please check if the code is all updated. The latest code of message.proto has the definition of sgxregisterreq:
   ` optional    SGXRegisterRequest sgxRegisterReq             = 14;
`

**Comment by trosan** [comment]
I am sorry, the file I referenced was auto-generated, thus I was mislead regarding the source of the error. The actual cause was that I had forgotten to perform a "make clean" after upgrading from 2.0.
